=== vishnuprasad2004/cli-resume/details-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type":"object",
    "description": "Resume Details",
    "properties": {
        "name": {
            "type":"string",
            "description": "Name of the person"
        },
        "about":{
            "type":"string"
        },
        "skills": {
            "type":"object",
            "properties": {
                "technicalSkills":{
                    "type":"array",
                    "description": "Add all the programming languages and domains in computer science",
                    "items": {
                        "type":"string"
                    }
                },
                "nonTechnicalSkills":{
                    "type":"array",
                    "description": "Add all the non-programming skills like designing and editing here",
                    "items": {
                        "type":"string"
                    }
                },
                "softSkills":{
                    "type":"array",
                    "description": "All all the soft skills like communication here",
                    "items": {
                        "type":"string"
                    }
                }
            },
            "description": "skills(technical, non technical, soft) of the person"
        },
        "educations":{
            "type":"object",
            "description": "Education of the person",
            "properties": {
                "graduation":{
                    "type":"object",
                    "description": "format => from *College name* semester, *semester no*",
                    "properties": {
                        "marks/grade" : {
                            "type":"string"
                        },
                        "details": {
                            "type":"string"
                        }
                    }
                },
                "intermediate": {
                    "type":"object",
                    "description": "format => from *school name* with",
                    "properties": {
                        "marks/grade" : {
                            "type":"string"
                        },
                        "details": {
                            "type":"string"
                        }
                    }
                },
                "matriculation" : {
                    "type":"object",
                    "description": "format => from *school name* with",
                    "properties": {
                        "marks/grade" : {
                            "type":"string"
                        },
                        "details": {
                            "type":"string"
                        }
                    }
                }
            }
        },
        "experiences":{
            "type":"array",
            "description": "Experience of the person",
            "items": {
                "type":"object",
                "properties": {
                    "companyName/InstituteName": {
                        "type":"string"
                    },
                    "details":{
                        "type":"string"
                    },
                    "timePeriod": {
                        "type":"string"
                    }
                }
            }
            
        },
        "projects":{
            "type":"array",
            "description": "Projects",
            "items": {
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "details":{
                        "type":"string"
                    },
                    "technologiesUsed": {
                        "type":"array",
                        "items": {
                            "type":"string"
                        }
                    },
                    "link":{
                        "type":"string",
                        "format": "uri"
                    }
                }
            }
        },
        "contacts":{
            "type":"object",
            "properties": {
                "github":{
                    "type":"string",
                    "format": "uri"
                },
                "linkedin":{
                    "type":"string",
                    "format": "uri"
                },
                "email": {
                    "type":"string",
                    "format": "email"
                }
            },
            "description": "Contacts"
        }
    }
}

=== vishnuprasad2004/cli-resume/src/details.json
{
    "$schema": "./details-schema.json",
    "name":"Vishnu Prasad Korada",
    "about": "Hello I am Vishnu Prasad Korada, pursuing Computer Science Engineering in GIETU\nI am a CSE sophmore specializing in AI/ML. I know Python, Java , HTML , CSS , JavaScript. I also know Graphic Designing and have used this skill in University Practically .\n Apart from that sketching, playing my piano and researching about space exploration are some of my favourite hobbies... ",
    "skills": {
        "technicalSkills": ["JavaScript", "C", "Java", "NodeJs", "ExpressJs", "Python", "HTML", "CSS"],
        "nonTechnicalSkills": ["Graphic Designing"],
        "softSkills": ["Communication", "Management"]
    },
    "educations": {
        "graduation":{
            "marks/grade":"9.14 CGPA",
            "details": "from Gandhi Institute of Engineering and Technology University, Gunupur with sem 1: "
        },
        "intermediate": {
            "marks/grade": "89%",
            "details": "from Gandhi Public School, Gunupur with "
        },
        "matriculation": {
            "marks/grade": "93%",
            "details": "from Laxman Public School, New Delhi with "
        }
    },
    "projects": [
        {
            "name": "Newsletter App",
            "details": "",
            "technologiesUsed": ["EJS", "NodeJs", "ExpressJs", "MongoDB"]
        },
        {
            "name": "Student Manager API",
            "details": "",
            "technologiesUsed": ["NodeJs", "ExpressJs", "MongoDB"]
        },
        {
            "name": "Space Invader Game",
            "details": "The Classic Space Invader Game, You can play now ... made with game classes and canvasAPI animation rendering",
            "technologiesUsed": ["HTML", "CSS", "JavaScript - canvasAPI Animations"],
            "link": "https://vishnuprasad2004.github.io/space-invader-game/"
        },
        {
            "name": "Audio Player Website",
            "details": "An Audio Player to play your local Music files.ðŸŽºðŸŽµðŸŽ¶",
            "technologiesUsed": ["HTML", "CSS", "JavaScript"],
            "link": "https://vishnuprasad2004.github.io/Audio-Player/"
        },
        {
            "name": "To Do List Website",
            "details": "a simple to do app with mobile responsiveness",
            "technologiesUsed": ["HTML", "CSS", "JavaScript"],
            "link": "https://vishnuprasad2004.github.io/to-Do-List/"
        },
        {
            "name": "Mental Maths Website",
            "details": "Mental Maths Quiz which prompts arithematic expressions with scores and timing",
            "technologiesUsed": ["HTML", "CSS", "JavaScript"],
            "link": "https://vishnuprasad2004.github.io/Mental-Maths-Quiz/"
        }
    ],
    "contacts": {
        "github": "http://github.com/vishnuprasad2004",
        "linkedin": "https://www.linkedin.com/in/vishnu-prasad-korada-32b550253",
        "instagram": "",
        "behance": "",
        "email": "vishnuprasadkorada@gmail.com"
    }
}
